name: npm test

on:
  - push

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm with pnpm install
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - name: Run pnpm install
        run: pnpm install
      - name: Run rome check
        run: pnpm lint
      - name: Run pnpm test
        run: pnpm test



