name: npm test

on:
  - push

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm with pnpm install
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.9.5
      - name: Run pnpm install
        run: pnpm install
      - name: Run pnpm test
        run: pnpm test



