name: Publish Package to npmjs
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    timeout-minutes: 30
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: main
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm with pnpm install
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 9.7.0  # renovate: depName=pnpm
          run_install: true
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
