name: Publish Package to npmjs
on:
  push:
    branch:
      - "main"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm with pnpm install
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - run: pnpm install
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
